### ISSUE TITLE
Add Default trait

### ISSUE THREAD

**Issue by kevaundray** [crate-crypto/Curve448#8]
Add default trait for curves and field struct

**Comment by roynalnaruto** [comment]
Hi,

Please review [this PR](https://github.com/crate-crypto/Curve448/pull/14)

**Comment by roynalnaruto** [comment]
[https://github.com/crate-crypto/Curve448/pull/14](url)

**Comment by roynalnaruto** [comment]
#14

**Comment by kevaundray** [comment]
Closing as PR has been merged.
